files:
    allowedExtensions:
        - .jpg
        - .jpeg
        - .png
        - .gif
        - .svg
        - .webp
        - .avif
        - .mp4
        - .webm
        - .mp3
        - .ogg
        - .m4a
