export function escapeRegExp(string) {
    return string.replace(/[-[\]/{}()*+?.\\^$|]/g, "\\$&");
}

export function makeDiacriticsRegExp(string) {
    const diacritics = {
        a: "[aáàăâǎåäãȧąāảȁạ]",
        b: "[bḃḅ]",
        c: "[cćĉčċç]",
        d: "[dďḋḑḍ]",
        e: "[eéèĕêěëẽėȩęēẻȅẹ]",
        g: "[gǵğĝǧġģḡ]",
        h: "[hĥȟḧḣḩḥ]",
        i: "[iiíìĭîǐïĩįīỉȉịı]",
        j: "[jĵǰ]",
        k: "[kḱǩķḳ]",
        l: "[lĺľļḷ]",
        m: "[mḿṁṃ]",
        n: "[nńǹňñṅņṇ]",
        o: "[oóòŏôǒöőõȯǿǫōỏȍơọ]",
        p: "[pṕṗ]",
        r: "[rŕřṙŗȑṛ]",
        s: "[sśŝšṡşṣș]",
        t: "[tťẗṫţṭț]",
        u: "[uúùŭûǔůüűũųūủȕưụ]",
        v: "[vṽṿ]",
        w: "[wẃẁŵẘẅẇẉ]",
        x: "[xẍẋ]",
        y: "[yýỳŷẙÿỹẏȳỷỵ]",
        z: "[zźẑžżẓ]",
    };
    for (const char in diacritics) {
        string = string.split(char).join(diacritics[char]);
        string = string.split(char.toUpperCase()).join(diacritics[char].toUpperCase());
    }
    return string;
}

export function makeSlug(string) {
    const translate = {
        "\t": "",
        "\r": "",
        "!": "",
        '"': "",
        "#": "",
        $: "",
        "%": "",
        "'": "-",
        "(": "",
        ")": "",
        "*": "",
        "+": "",
        ",": "",
        ".": "",
        ":": "",
        ";": "",
        "<": "",
        "=": "",
        ">": "",
        "?": "",
        "@": "",
        "[": "",
        "]": "",
        "^": "",
        "`": "",
        "{": "",
        "|": "",
        "}": "",
        "¡": "",
        "£": "",
        "¤": "",
        "¥": "",
        "¦": "",
        "§": "",
        "«": "",
        "°": "",
        "»": "",
        "‘": "",
        "’": "",
        "“": "",
        "”": "",
        "\n": "-",
        " ": "-",
        "-": "-",
        "–": "-",
        "—": "-",
        "/": "-",
        "\\": "-",
        _: "-",
        "~": "-",
        À: "A",
        Á: "A",
        Â: "A",
        Ã: "A",
        Ä: "A",
        Å: "A",
        Æ: "Ae",
        Ç: "C",
        Ð: "D",
        È: "E",
        É: "E",
        Ê: "E",
        Ë: "E",
        Ì: "I",
        Í: "I",
        Î: "I",
        Ï: "I",
        Ñ: "N",
        Ò: "O",
        Ó: "O",
        Ô: "O",
        Õ: "O",
        Ö: "O",
        Ø: "O",
        Œ: "Oe",
        Š: "S",
        Þ: "Th",
        Ù: "U",
        Ú: "U",
        Û: "U",
        Ü: "U",
        Ý: "Y",
        à: "a",
        á: "a",
        â: "a",
        ã: "a",
        ä: "ae",
        å: "a",
        æ: "ae",
        "¢": "c",
        ç: "c",
        ð: "d",
        è: "e",
        é: "e",
        ê: "e",
        ë: "e",
        ì: "i",
        í: "i",
        î: "i",
        ï: "i",
        ñ: "n",
        ò: "o",
        ó: "o",
        ô: "o",
        õ: "o",
        ö: "oe",
        ø: "o",
        œ: "oe",
        š: "s",
        ß: "ss",
        þ: "th",
        ù: "u",
        ú: "u",
        û: "u",
        ü: "ue",
        ý: "y",
        ÿ: "y",
        Ÿ: "y",
    };
    string = string.toLowerCase();
    for (const char in translate) {
        string = string.split(char).join(translate[char]);
    }
    return string
        .replace(/[^a-z0-9-]/g, "")
        .replace(/^-+|-+$/g, "")
        .replace(/-+/g, "-");
}

export function validateSlug(slug) {
    return slug
        .toLowerCase()
        .replace(" ", "-")
        .replace(/[^a-z0-9-]/g, "");
}
