name: Check panel assets

on:
  push:
    branches:
      - 2.x
    paths:
      - "panel/src/**"

  pull_request:
    branches:
      - 2.x
    paths:
      - "panel/src/**"

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          package-json-file: panel/package.json
          cache: true
          cache-dependency-path: panel/pnpm-lock.yaml
          install: false

      - name: Install dependencies
        run: |
          cd panel
          pnpm install

      - name: Check TypeScript
        run: |
          cd panel
          pnpm run check:ts

      - name: Check CSS
        run: |
          cd panel
          pnpm run check:css
