name: Check panel assets

on:
  push:
    branches:
      - 2.x
    paths:
      - "panel/src/**"

  pull_request:
    branches:
      - 2.x
    paths:
      - "panel/src/**"

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: latest
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install dependencies
        run: |
          cd panel
          pnpm install

      - name: Check TypeScript
        run: |
          cd panel
          pnpm run check:ts

      - name: Check CSS
        run: |
          cd panel
          pnpm run check:css
